---
env:
  contexts:
    - name: "Default Context"
      urls:
        - "http://testfire.net/"
      includePaths:
        - "http://testfire.net/.*"
        - "http://testfire.net/*"
      excludePaths: []
      authentication:
        method: "form"
        parameters:
          loginPageUrl: "http://testfire.net/login.jsp"
          loginRequestUrl: "http://testfire.net/doLogin"
          loginRequestBody: "uid={%username%}&passw={%password%}"
        verification:
          method: "response"
          loggedInRegex: "Sign Off"
          loggedOutRegex: "Sign In"
          pollFrequency: 60
          pollUnits: "requests"
          pollUrl: ""
          pollPostData: ""
      sessionManagement:
        method: "cookie"
        parameters: {}
      technology:
        exclude: []
      users:
        - name: "test_user"
          credentials:
            password: "demo1234"
            username: "jsmith"
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
    vars:
      EnvironmentID: "y9jeiidiodsu"
      AstAPIKey: "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI5Y2Y1YmI0NC1iMTNlLTQzYWQtOWQyYy1lYjk2NTlkN2EzZTIifQ.eyJpYXQiOjE3MDQxNzUyNjAsImp0aSI6IjE5NzFhNGE1LTI0ODYtNGU1Yy04OWMzLTNiNGQ4ZTNkNjMwNyIsImlzcyI6Imh0dHBzOi8vZXUuaWFtLmNoZWNrbWFyeC5uZXQvYXV0aC9yZWFsbXMvZHBfd3BfYWNjb3VudCIsImF1ZCI6Imh0dHBzOi8vZXUuaWFtLmNoZWNrbWFyeC5uZXQvYXV0aC9yZWFsbXMvZHBfd3BfYWNjb3VudCIsInN1YiI6IjI0N2E1NTBhLWNmOTMtNGQzZC05YzdkLTA2NTMzZDBiMzNmOSIsInR5cCI6Ik9mZmxpbmUiLCJhenAiOiJhc3QtYXBwIiwic2Vzc2lvbl9zdGF0ZSI6IjQzMDU3ZjA1LTBlNzctNGZkNi1iZjM1LWI4OTJiOGY1NzJjZCIsInNjb3BlIjoiIG9mZmxpbmVfYWNjZXNzIiwic2lkIjoiNDMwNTdmMDUtMGU3Ny00ZmQ2LWJmMzUtYjg5MmI4ZjU3MmNkIn0.7oMXktcgl9f1EBR8fJkMHrN_3zzOHkbvGo1_saNZijc"
  jobs:
    - parameters:
        maxAlertsPerRule: 0
        scanOnlyInScope: true
        maxBodySizeInBytesToScan: 0
        enableTags: false
      rules: []
      name: "passiveScan-config"
      type: "passiveScan-config"
    # ... (other job configurations)
