name: DAST Scan

on:
  push:
  pull_request:

jobs:
  dast_scan:
    name: Run DAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Grant permissions to create directory
        run: chmod -R 777 $GITHUB_WORKSPACE
      
      - name: Run DAST Web Scan
        uses: checkmarx/dast-github-action@main
        with:
          config: 'zapconfig.yaml'
          command: web
          base_url: https://eu.ast.checkmarx.net
          environment_id: y9jeiidiodsu
          verbose: true
          AstAPIKey: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI5Y2Y1YmI0NC1iMTNlLTQzYWQtOWQyYy1lYjk2NTlkN2EzZTIifQ.eyJpYXQiOjE3MDQxNzUyNjAsImp0aSI6IjE5NzFhNGE1LTI0ODYtNGU1Yy04OWMzLTNiNGQ4ZTNkNjMwNyIsImlzcyI6Imh0dHBzOi8vZXUuaWFtLmNoZWNrbWFyeC5uZXQvYXV0aC9yZWFsbXMvZHBfd3BfYWNjb3VudCIsImF1ZCI6Imh0dHBzOi8vZXUuaWFtLmNoZWNrbWFyeC5uZXQvYXV0aC9yZWFsbXMvZHBfd3BfYWNjb3VudCIsInN1YiI6IjI0N2E1NTBhLWNmOTMtNGQzZC05YzdkLTA2NTMzZDBiMzNmOSIsInR5cCI6Ik9mZmxpbmUiLCJhenAiOiJhc3QtYXBwIiwic2Vzc2lvbl9zdGF0ZSI6IjQzMDU3ZjA1LTBlNzctNGZkNi1iZjM1LWI4OTJiOGY1NzJjZCIsInNjb3BlIjoiIG9mZmxpbmVfYWNjZXNzIiwic2lkIjoiNDMwNTdmMDUtMGU3Ny00ZmQ2LWJmMzUtYjg5MmI4ZjU3MmNkIn0.7oMXktcgl9f1EBR8fJkMHrN_3zzOHkbvGo1_saNZijc
        
