name: DAST Scan

# This workflow will run when a push or pull request is made to the repository
on:
  push:
  pull_request:

jobs:
  dast_scan:
    name: Run DAST Scan
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      # Run DAST with Checkmarx action
      - name: Run DAST Web Scan
        uses: checkmarx/dast-github-action@main
        with:
          config: 'zapconfig.yaml'
          command: web
          base_url: https://eu.ast.checkmarx.net
          environment_id: y9jeiidiodsu
          verbose: true
