 # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Scan with DAST
    - name: run dast web
      uses: checkmarx/dast-action@latest
      with:
        config: 'zapconfig.yaml'
        verbose: true
